USE dtb_ss02;

CREATE TABLE ORDERS (
	order_id INT AUTO_INCREMENT PRIMARY KEY,
    order_date DATE DEFAULT (CURRENT_DATE),
    CustomerID INT NOT NULL,
	CONSTRAINT FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);