USE dtb_ss02;

CREATE TABLE CUSTOMERS (
    CustomerID INT PRIMARY KEY,
    FullName VARCHAR(100),
    Email VARCHAR(100),  
    Age INT             
);

ALTER TABLE CUSTOMERS
MODIFY Email VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS
ADD CONSTRAINT chk_age CHECK (Age >= 0);